"""QA-only (CHK-LIKE4LIKE, CHK-NUMBERS): read the it1 and it2 gate.json files and write a side-by-side
table. Every number comes mechanically from the two gate.json files; nothing is typed by hand.
Writes qa/probe/like4like_it1_it2.json and prints a Markdown section (appended to VERDICT.md)."""
import hashlib, json
g1 = json.load(open("_it1_SUPERSEDED/qa/gate.json")); g2 = json.load(open("qa/gate.json"))
def h(p): return hashlib.sha256(open(p, "rb").read()).hexdigest()[:12]
rows = []
def st(g, item):
    for r in g["gated_results"]:
        if r["item"] == item: return r["stats"], r["result"]["pass"]
    return None, None
items = [r["item"] for r in g2["gated_results"]]
for it in items:
    a, pa = st(g1, it); b, pb = st(g2, it)
    rows.append({"item": it, "it1": {k: a[k] for k in ("n", "p95", "max")} if a else None, "it1_pass": pa,
                 "it2": {k: b[k] for k in ("n", "p95", "max")}, "it2_pass": pb})
extra = {}
for k, f in (("registration", lambda g: {x: g["registration"][x] for x in ("iterations", "max_iterations", "converged", "delta_deg", "delta_mm")}),
             ("datum_audit", lambda g: {x: g["datum_audit"][x] for x in ("angle_deg", "origin_offset_mm", "point_disagreement_p95_mm", "point_disagreement_max_mm")}),
             ("unobservable_fraction", lambda g: g["deviation"]["unobservable_fraction"]),
             ("cad_to_scan_raw", lambda g: {x: g["deviation"]["cad_to_scan"][x] for x in ("p95", "max")}),
             ("datum_frame_scan_to_cad", lambda g: {x: g["deviation_datum_frame"]["scan_to_cad"][x] for x in ("p95", "max")}),
             ("n_over_0.8_scan_to_cad", lambda g: g["deviation"]["over_band_clusters"]["scan_to_cad"]["n_over"]),
             ("clusters_ge20", lambda g: g["deviation"]["over_band_clusters"]["scan_to_cad"]["n_clusters_ge_min"]),
             ("faces", lambda g: list(g["surface_census"].values())[0].get("faces") if g.get("surface_census") else None),
             ("verdict", lambda g: g["verdict"])):
    extra[k] = {"it1": f(g1), "it2": f(g2)}
out = {"it1_gate": {"sha256_12": h("_it1_SUPERSEDED/qa/gate.json"), "created": g1["created"]},
       "it2_gate": {"sha256_12": h("qa/gate.json"), "created": g2["created"]},
       "protocol": "identical (see review.json CHK-LIKE4LIKE)", "gated": rows, "other": extra}
json.dump(out, open("qa/probe/like4like_it1_it2.json", "w"), indent=1)
f = lambda v: "—" if v is None else (f"{v:.3f}" if isinstance(v, float) else str(v))
P = lambda p: {True: "PASS", False: "FAIL", None: "—"}[p]
L = ["", "## It1 vs it2, same protocol (CHK-LIKE4LIKE; generated by qa/probe/like4like_it1_it2.py from both gate.json files)", "",
     f"it1 gate `_it1_SUPERSEDED/qa/gate.json` sha256 {out['it1_gate']['sha256_12']}…; it2 gate `qa/gate.json` sha256 {out['it2_gate']['sha256_12']}….", "",
     "| Gated item | it1 p95 | it1 max | it1 | it2 p95 | it2 max | it2 |", "|---|---|---|---|---|---|---|"]
for r in rows:
    a = r["it1"] or {}
    L.append(f"| {r['item']} | {f(a.get('p95'))} | {f(a.get('max'))} | {P(r['it1_pass'])} | {f(r['it2']['p95'])} | {f(r['it2']['max'])} | {P(r['it2_pass'])} |")
L += ["", "| Other | it1 | it2 |", "|---|---|---|"]
for k, v in extra.items():
    fmt = lambda x: ", ".join(f"{kk} {f(vv)}" for kk, vv in x.items()) if isinstance(x, dict) else f(x)
    L.append(f"| {k} | {fmt(v['it1'])} | {fmt(v['it2'])} |")
print("\n".join(L))
