import json
R = {
 "verdict": "REVISE",
 "revise_route": "geometry",
 "iteration": 3,
 "loop_note": "loop 3 of 3 is used: per the orchestrator rule this REVISE becomes HALT. It is written as REVISE because a geometric cause the builder could fix remains (Z4 scan->CAD), not because more loops are available.",
 "independence": "fresh agent (stl-re-verify stage, iteration 3) that did not build the model; QA scripts from stl-re-verify only plus run-local report-only probes in qa/ (it2_it3_diff.py, zone_probe.py, attribution_probe.py, datum_crosscheck.py adapted from _it2_SUPERSEDED/qa/); own ICP on the it3 STEP; builder numbers, build_log.txt, measure/params.json values and scratchpad files not read; build/model.py only grepped read-only (loft ruled / polyline / sweep); the builder's 'only three features changed' claim was checked on the STEPs (qa/it2_it3_diff.json), not taken from params or the plan.",
 "checks": {
  "CHK-CIRCULAR": {"ran": True, "result": "finding", "note": "QA grading is independent: own ICP of the it3 CAD onto the full-res scan (T_refine QA-only, never written back), datum re-derived from the raw scan, no expected value taken from builder params. Finding (carried from it1/it2): the builder's record (MODELING_PLAN §0/§8 self-check passes; it3 re-measurements in measure/figures/measure_it3.json of the same scan) is a scan-derived consistency check, not independent evidence."},
  "CHK-LIKE4LIKE": {"ran": True, "result": "pass", "note": "it2 -> it3 compared under the SAME protocol as it1/it2: qa/regime.json (cp of intake/regime.json), masks.json (M1 pre-declared D1 box x 6.5..13 z -15..-1, both directions; M2 open boundary 0.8 mm, CAD->scan, QA-added at it1), zones.json, icp_scan_masks.json and datum_spec.json are byte-identical copies of _it2_SUPERSEDED/qa/ (which were byte-identical to it1). ICP params identical (ns 3M seed 11, nc 300k seed 13, normal 70 deg, boundary 0.8, corr 3.0, cap 60, tol 1e-6); deviation sampling identical (all 251631 scan verts, c2s 300k seed 2, k 8, n_samp 3M seed 0, no vertex candidates); observability identical (20000 seed 5, far 0.5, cone 60, 6 rays, offset 0.05, unbounded); sweep radii 0,0.2,0.4,0.8,1.5,2.5 and cluster params (0.8 mm, eps 1.0, min 20) identical; the it2 overlay panel sets re-drawn identically (overlay_rod, overlay_lower, overlay_it2_extra) plus 8 new it3 panels (overlay_it3_extra). Datum audit and datum_crosscheck reproduce it2 exactly (same alignment.json). Not like-for-like by construction: ICP re-run on the new CAD (it2 49 its 0.060 deg/0.053 mm, it3 44 its 0.053 deg/0.059 mm) and seeded CAD samples fall on a different surface, so M2 and the observable subsample select different points. Probe changes: zone_probe.py chunk 20000 -> 2000 (OOM on the finer it3 tessellation; chunking does not change results); attribution_probe.py adds a scan->CAD Z4 face attribution. Improvements in Z2/Z3 come from geometry (STEP diff confines the change to the bend, the paddle and the tip neck), not from protocol."},
  "CHK-INDEP": {"ran": True, "result": "pass", "note": "fresh agent; see independence"},
  "CHK-FILLET": {"ran": True, "result": "pass", "note": "build/export_check.json (it3): F03 lug corner 0.6 target = 0.6 used OK; F05 plate perimeter round 1.946 target = 1.946 used OK (it2: 1.2 assumed). Z3 now reads p95 0.134 scan->CAD (zone_probe: perimeter mean signed +0.048 vs +0.177 in it2), so the measured radius is confirmed by the gate. Lug radius still ASSUMED."},
  "CHK-PATCHWORK": {"ran": True, "result": "finding", "note": "census (QA, both frames): 122 faces (it2 109); plane 47, cone 33, cylinder 31, bspline 5, revolution 3, sphere 2, torus 1; analytic share 77.2 % by QA's count (it2 83.3 %; the bend torus was replaced by one bspline sweep face, area 331). No loft(ruled=True) (model.py:140 ruled=False, the planned fairing loft); no slice stack. New in it3: the bend is ONE sweep of a circle along a spline through 10 scanned centreline stations (model.py:249-258) - a fitted path, not a slice stack, accepted. Minor findings: (a) the bend radius bend_tube_r differs from the straight tube radius, which leaves two small annular ledges (qa/it2_it3_diff.json: two new PLANE faces of 1.61 mm2 at the bend ends) - a modelling artefact, not a scanned feature; (b) carried from it1: the rod bead/groove z 9.75..12.75 is a revolved measured (z,r) polyline."},
  "CHK-ENUM": {"ran": True, "result": "finding", "note": "all 12 intake features exist in the it3 CAD (overlays); D1 not modelled by declaration; the it3 tip neck under the bushing is new and is supported by the scan (Z4 hub cells t -10..-8, r<3.5 no longer over band; zone_probe). Finding: a coherent one-signed scan->CAD group at the tube-C entry on the bushing top (nearest CAD face 64, bushing top cone, 895 of 3477 points > 0.3 mm, 100 % scan OUTSIDE the CAD, d max 0.724; tube C end face 60 adds 122 more) shows material the CAD lacks: overlay Z=-33.5 shows the scan bulging 0.3-0.7 mm beyond the CAD around the tube entry, and photo_1 shows a raised collar on the bushing top around the tube. Not modelled -> part of the Z4 scan->CAD miss."},
  "CHK-ACHIEVABLE": {"ran": True, "result": "n/a", "note": "no Tier-1 (no calipers)"},
  "PHOTO-PLAUSIBILITY": {"ran": True, "result": "pass", "note": "photo_1, photo_2 walked by this agent: tapered rod with O-rings, knob, paddle with dish, sleeve + sealing band, steel tube with one bend, white bushing (ribbed/windowed tip-side face and a raised collar where the tube enters, photo_1), steel tip with open bore - all present in CAD except the bushing-top collar (see CHK-ENUM). Torn flap at the knob/sleeve junction visible in both photos (supports M1/D1). Window floors and bore depth not visible. No scale reference."}
 },
 "photos": ["input/photos/photo_1.webp", "input/photos/photo_2.webp"],
 "cluster_explanations": {
  "0": "D1 torn rubber flash, -y side of the sleeve (centroid x 10.3, z -5.9): specimen damage pre-declared at intake, visible in photo_1/photo_2 and overlay x=10 / Z=-8; inside mask M1. Artefact, not a missing feature (same as it1/it2 cluster 0).",
  "1": "D1 torn rubber flash, +y side of the sleeve (centroid x 9.1, z -9.0): same flap, same evidence; inside mask M1 (same as it1/it2 cluster 1)."
 },
 "limitations": [
  {"id": "L1", "text": "Scan-only: no calipers, Tier-1 not run, absolute scale not caliper-verified (units assumed mm; DECISIONS MEASUREMENTS, CHK-SCALE finding at intake).", "rerun_trigger": "any caliper reading (>=3 envelope dims for a scale test) -> re-run Tier-1 and scale check"},
  {"id": "L2", "text": "Masks. M1 D1 torn flash (pre-declared box, both directions) removes 6.74 % of scan->CAD points (inside p95 2.98 / max 4.52 mm) and 4.07 % of CAD->scan points; the box also hides intact sleeve/knob-fairing surface. Whole-part scan->CAD PASSES ONLY MASKED (masked p95 0.236 / max 0.737; UNMASKED p95 0.312 / max 4.518 mm, over the band). Zone Z1 CAD->scan passes only with the QA-added M2 open-boundary mask (masked p95 0.133 / max 0.693; UNMASKED p95 0.501 / max 1.689). Zone Z2 CAD->scan passes only with M2 (masked p95 0.214 / max 0.345; UNMASKED p95 0.228 / max 0.802, 0.002 over; M1 does not reach Z2, so M2 alone removes it). M2 (CAD->scan only) removes 16.94 %.", "rerun_trigger": "rescan with the torn flap trimmed or pressed back (or a replacement part), and a supplementary scan covering the 33 hole loops (rod theta 180..260, bushing top / tube entry) -> re-run unmasked"},
  {"id": "L3", "text": "Unobservable/uncovered CAD: tip bore interior (13.6 mm, builder-declared scan lower bound), bushing underside window pockets (2.52 mm, scan lower bound) and their floors, hidden assembly interfaces (PART-CLASS), 33 scan holes. The OD ray-cone heuristic (subsample 20000 seed 5, far 0.5, cone 60, 6 rays, offset 0.05, unbounded) marks only 1.72 % unobservable, so these surfaces remain inside the gated 'observable' CAD->scan number.", "rerun_trigger": "a pin-gauge/depth reading of the tip bore and of one window pocket, or a supplementary scan of the bushing underside -> re-run CAD->scan"},
  {"id": "L4", "text": "Datum audit (report-only) outside the RE_SPEC reference: normals-eigen axis 0.42 deg / origin 0.33 mm vs the builder (identical to it1/it2, same alignment.json); QA section-circle cross-check (qa/datum_crosscheck.json, identical to it2) agrees to 0.04 deg / 0.03 mm, tube clock -0.56 deg. ICP correction small (0.053 deg / 0.059 mm). The Z4 scan->CAD p95 is frame-sensitive at the band edge: 0.297 in the builder datum frame (qa/deviation_datum.json, not gated) vs 0.301 after QA ICP (gated).", "rerun_trigger": "any datum change at intake -> re-run the whole QA"},
  {"id": "L5", "text": "Overlays are drawn in the builder's alignment frame (overlay.py has no --registration input); the ICP correction is 0.059 mm, below the line widths.", "rerun_trigger": "if the ICP correction ever exceeds 0.1 mm -> redraw overlays in the registered frame"}
 ],
 "miss_explanations": [
  {"region": "Z4 bushing + tip scan->CAD (p95 0.301 > 0.30 by <0.001 mm; max 0.737 in band) -- FIXABLE (geometry), marginal", "cause": "Coherent, one-signed residual groups, all with the scan OUTSIDE the CAD (CAD too small): (1) the tube-C entry on the bushing top: nearest face 64 (bushing top cone) 895 of 3477 points > 0.3 mm, 100 % outside, d max 0.724, plus 122 points on the tube C end (face 60), t -22.3..-21.4 / r 2.2..6.6 about the tip axis; overlay Z=-33.5 shows a smooth bulge 0.3-0.7 mm beyond the CAD around the tube entry and photo_1 shows a raised collar there - a missing feature, not modelled. 75 % of these points lie within 0.8 mm of a scan-hole edge (hole loop r 35.5..37.9, z -33..-30.4), so part could be edge curl, but the sign is 100 % one-sided and the photo supports a collar. (2) The bushing barrel underside rim (face 68, t -12.8..-8.6, r 7.5..10.2): 597 points > 0.3, 78 % outside - named in it2 ('barrel/rim r 5..9.5') and not addressed in it3. Report-only what-if (qa/attribution_probe.json): either group at the zone median gives Z4 p95 0.272/0.273. The it3 tip neck fixed the hub (it2 cells t -10..-8, r<3.5: 632 points > 0.3 -> 79). Z4 scan->CAD away from scan-hole edges reads p95 0.247. The miss is frame-sensitive (datum frame 0.297, not gated).", "options": "REVISE geometry (no loop left -> HALT): model the bushing-top collar around the tube entry (measure it from sections Z=-32..-35 and x=40) and refit the barrel underside rim; or a supplementary scan of the bushing top to confirm the collar vs hole-edge curl; or accept the 0.001 mm p95 excess (ACCEPT-BAND, human decision)."},
  {"region": "Whole-part observable CAD->scan (p95 0.766 / max 2.601) and Z4 CAD->scan (p95 1.063 masked / 1.571 unmasked, max 2.602/2.617) -- NOT fixable by geometry", "cause": "CAD surface with no scan behind it. Z4: 13892 of 13992 over-0.8 CAD samples lie on the 32 window-pocket/bore faces introduced in it2 (unchanged in it3); the other Z4 faces away from scan holes read p95 0.241 / max 0.511 (qa/attribution_probe.json). Whole part: with D1, scan-hole-adjacent (0.8 mm) and bore points removed CAD->scan reads p95 0.233 / max 2.602, the max being the window floors (unscanned; overlays x=44.4, Z=-43.5, Z=-44.4). Hole-adjacent samples: 50870, p95 1.628. The it3 changes (bend, paddle, neck) do not touch these surfaces; observable p95 moved 0.736 -> 0.766 because the ICP and the seeded CAD samples changed (same protocol, different CAD).", "options": "cannot be fixed by geometry: any pocket/bore depth leaves an unscanned floor/wall. Pin-gauge/depth readings of the bore and one window (then model the measured depth), a supplementary scan of the bushing underside, or accept with L3 declared (ACCEPT-BAND). A shallower model brings back the it1 scan->CAD clusters."},
  {"region": "Whole-part scan->CAD UNMASKED (p95 0.312 / max 4.518; gated masked number passes) -- NOT fixable by geometry", "cause": "D1 torn flash (clusters 0 and 1: 5721 of 5721 over-band points), specimen damage, deliberately not modelled.", "options": "rescan a clean specimen, or accept with M1 declared (ACCEPT-BAND)."}
 ],
 "claim_boundary": "Iteration-3 CAD is NOT approved. It is a scan-only, uncalipered reconstruction of a damaged assembly specimen: not fit for tooling or for the fit-critical machine interface (rod spigot / O-ring seats) until calipered; the tip bore depth (13.6) and window depth (2.52) are scan lower bounds, not measured depths; the bushing-top collar at the tube entry is not modelled; hidden internal interfaces are not modelled; the one-fused-solid STEP is not a multi-body assembly. The whole-part scan->CAD pass and the Z1/Z2 CAD->scan passes are masked passes."
}
json.dump(R, open("qa/review.json", "w"), indent=1, ensure_ascii=False)
