"""Render docs/img/step_progress.svg (scan → STEP progress board) from docs/bom.csv.

Every part with CAD = SCAN is one row; its `status` column decides the stages:

    todo       scan open
    scanned    scan done, STEP rebuild in progress
    modeled    scan + STEP + deviation gate done, check-fixture open
    validated  all four stages done
    deferred   greyed out (phase 2)

Usage:  python tools/build_progress.py          # rewrite the SVG
        python tools/build_progress.py --check  # exit 1 if the SVG is stale
"""
import csv
import re
import sys
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV = ROOT / "docs" / "bom.csv"
SVG = ROOT / "docs" / "img" / "step_progress.svg"

STAGES = ["Scan", "STEP rebuild", "Deviation gate", "Check-fixture"]
STAGE_HINT = ["raw STL + calipers", "parametric CAD", "CAD ↔ scan", "printed fit test"]
STATE = {  # status -> state of each stage
    "todo":      ["open", "open", "open", "open"],
    "scanned":   ["done", "active", "open", "open"],
    "modeled":   ["done", "done", "done", "open"],
    "validated": ["done", "done", "done", "done"],
    "deferred":  ["deferred"] * 4,
}

W, ROW, TOP, LEFT = 1120, 36, 214, 40
NAME_W = 380
COL_W = (W - LEFT * 2 - NAME_W) // 4

COLORS = {
    "done":     ("#e3f4e1", "#3f9a4a", "#2c6e34", "✓ done"),
    "active":   ("#fff3d6", "#e0a526", "#8a5d00", "● in progress"),
    "open":     ("#ffffff", "#d3d9e0", "#9aa3ad", "open"),
    "deferred": ("#f1f3f5", "#e1e5ea", "#b3bac2", "phase 2"),
}


def short(name, n=44):
    name = re.sub(r"\*\*|—\s*$", "", name).strip(" —")
    name = re.sub(r"\s*\(.*?\)", "", name) if len(name) > n else name
    return name if len(name) <= n else name[: n - 1] + "…"


def render(rows):
    parts = [r for r in rows if r["cad"] == "SCAN"]
    live = [r for r in parts if r["status"] != "deferred"]
    total = len(live) * 4
    done = sum(STATE[r["status"]].count("done") for r in live)
    modeled = sum(r["status"] in ("modeled", "validated") for r in live)
    h = TOP + len(parts) * ROW + 70
    o = []
    add = o.append
    add(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {h}" width="{W}" height="{h}" '
        'font-family="Helvetica, Arial, sans-serif">')
    add("  <title>Open Dedica — scan to STEP progress</title>")
    add("  <!-- Generated by tools/build_progress.py from docs/bom.csv — do not edit by hand. -->")
    add(f'  <rect width="{W}" height="{h}" fill="#ffffff"/>')
    add(f'  <text x="{LEFT}" y="50" font-size="26" font-weight="700" fill="#1f2733">'
        "Scan → STEP library progress</text>")
    add(f'  <text x="{LEFT}" y="76" font-size="14" fill="#5b6572">Every scanned part: raw scan → '
        "parametric STEP → deviation gate → printed check-fixture · status from docs/bom.csv</text>")

    # overall bar
    bw = W - LEFT * 2
    pct = done / total if total else 0
    add(f'  <rect x="{LEFT}" y="98" width="{bw}" height="16" rx="8" fill="#eef1f5"/>')
    add(f'  <rect x="{LEFT}" y="98" width="{max(16, round(bw * pct))}" height="16" rx="8" fill="#3f9a4a"/>')
    add(f'  <text x="{LEFT}" y="138" font-size="14" fill="#1f2733"><tspan font-weight="700">'
        f"{modeled} / {len(live)}</tspan> parts modeled · <tspan font-weight=\"700\">{done} / {total}"
        f"</tspan> stages done ({pct:.0%})</text>")

    # header
    y = TOP - 30
    add(f'  <text x="{LEFT}" y="{y}" font-size="12" font-weight="700" fill="#5b6572">PART</text>')
    for i, (s, hint) in enumerate(zip(STAGES, STAGE_HINT)):
        cx = LEFT + NAME_W + COL_W * i + COL_W // 2
        add(f'  <text x="{cx}" y="{y - 14}" font-size="13" font-weight="700" fill="#1f2733" '
            f'text-anchor="middle">{i + 1}. {s}</text>')
        add(f'  <text x="{cx}" y="{y + 2}" font-size="11" fill="#6b7582" text-anchor="middle">{hint}</text>')
    add(f'  <path d="M{LEFT} {TOP - 16}H{W - LEFT}" stroke="#d3d9e0" stroke-width="1.5"/>')

    for n, r in enumerate(parts):
        y = TOP + n * ROW
        states = STATE[r["status"]]
        if n % 2:
            add(f'  <rect x="{LEFT - 8}" y="{y - 6}" width="{W - LEFT * 2 + 16}" height="{ROW}" rx="6" fill="#f7f9fb"/>')
        grey = r["status"] == "deferred"
        add(f'  <text x="{LEFT}" y="{y + 17}" font-size="13" font-weight="700" '
            f'fill="{"#b3bac2" if grey else "#2f6db5"}" font-family="Menlo,Consolas,monospace">{r["part_no"]}</text>')
        add(f'  <text x="{LEFT + 76}" y="{y + 17}" font-size="13.5" fill="{"#9aa3ad" if grey else "#1f2733"}">'
            f"{escape(short(r['name']))}</text>")
        if r["issue"]:
            add(f'  <text x="{LEFT + NAME_W - 14}" y="{y + 17}" font-size="12" fill="#9aa3ad" '
                f'text-anchor="end">{escape(r["issue"])}</text>')
        for i, st in enumerate(states):
            fill, stroke, ink, label = COLORS[st]
            x = LEFT + NAME_W + COL_W * i + 8
            dash = ' stroke-dasharray="4 3"' if st == "open" else ""
            add(f'  <rect x="{x}" y="{y}" width="{COL_W - 16}" height="{ROW - 12}" rx="12" fill="{fill}" '
                f'stroke="{stroke}" stroke-width="1.5"{dash}/>')
            add(f'  <text x="{x + (COL_W - 16) // 2}" y="{y + 16}" font-size="12" font-weight="700" '
                f'fill="{ink}" text-anchor="middle">{label}</text>')

    y = TOP + len(parts) * ROW + 30
    add(f'  <text x="{LEFT}" y="{y}" font-size="12.5" fill="#5b6572">Want to help? Pick an '
        '<tspan font-weight="700">open</tspan> cell → comment on the part\'s issue → see CONTRIBUTING.md</text>')
    add(f'  <text x="{W - LEFT}" y="{y}" font-size="11" fill="#9aa3ad" text-anchor="end">CC BY 4.0 · open-dedica</text>')
    add("</svg>")
    return "\n".join(o) + "\n"


def main():
    rows = list(csv.DictReader(CSV.open(encoding="utf-8")))
    bad = [r["part_no"] for r in rows if r["cad"] == "SCAN" and r["status"] not in STATE]
    if bad:
        print("unsupported status for SCAN parts: " + ", ".join(bad))
        sys.exit(1)
    text = render(rows)
    if "--check" in sys.argv:
        if not SVG.exists() or SVG.read_text(encoding="utf-8") != text:
            print("docs/img/step_progress.svg is stale — run: python tools/build_progress.py")
            sys.exit(1)
        print("OK — progress board up to date")
        return
    SVG.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {SVG.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
